using FlashShop.Notification.Api.Entities;
using Microsoft.EntityFrameworkCore;

namespace FlashShop.Notification.Api.Data;

public static class DataSeeder
{
    public static async Task SeedAsync(NotificationDbContext context)
    {
        var existingKeys = await context.NotificationTemplates.Select(t => t.Key).ToListAsync();

        var templates = new List<NotificationTemplate>();

        if (!existingKeys.Contains("OrderAwaitingPayment"))
        {
            templates.Add(new NotificationTemplate
            {
                Id = Guid.NewGuid(),
                Key = "OrderAwaitingPayment",
                Subject = "Your order {{OrderNumber}} is awaiting payment",
                IsActive = true,
                Body = """
                <h2>Order Awaiting Payment</h2>
                <p>Dear Customer,</p>
                <p>Your order <strong>{{OrderNumber}}</strong> has been confirmed and is awaiting payment.</p>
                <p>Total Amount: <strong>{{TotalAmount}} VND</strong></p>
                <p>Please complete payment before: <strong>{{PaymentDeadline}}</strong></p>
                <br/>
                <p>Best regards,<br/>FlashShop Team</p>
                """
            });
        }

        if (!existingKeys.Contains("OrderPaid"))
        {
            templates.Add(new NotificationTemplate
            {
                Id = Guid.NewGuid(),
                Key = "OrderPaid",
                Subject = "Payment confirmed for order {{OrderNumber}}",
                IsActive = true,
                Body = """
                <h2>Payment Confirmed</h2>
                <p>Dear Customer,</p>
                <p>Your payment for order <strong>{{OrderNumber}}</strong> has been confirmed.</p>
                <p>Total Amount: <strong>{{TotalAmount}} VND</strong></p>
                <p>Your order is now being processed for shipping.</p>
                <br/>
                <p>Best regards,<br/>FlashShop Team</p>
                """
            });
        }

        if (!existingKeys.Contains("OrderOutOfStock"))
        {
            templates.Add(new NotificationTemplate
            {
                Id = Guid.NewGuid(),
                Key = "OrderOutOfStock",
                Subject = "Your order {{OrderNumber}} could not be fulfilled",
                IsActive = true,
                Body = """
                <h2>Order Could Not Be Fulfilled</h2>
                <p>Dear Customer,</p>
                <p>Unfortunately, your order <strong>{{OrderNumber}}</strong> could not be fulfilled due to insufficient stock.</p>
                <br/>
                <p>Best regards,<br/>FlashShop Team</p>
                """
            });
        }

        if (!existingKeys.Contains("OrderCancelled"))
        {
            templates.Add(new NotificationTemplate
            {
                Id = Guid.NewGuid(),
                Key = "OrderCancelled",
                Subject = "Your order {{OrderNumber}} has been cancelled",
                IsActive = true,
                Body = """
                <h2>Order Cancelled</h2>
                <p>Dear Customer,</p>
                <p>Your order <strong>{{OrderNumber}}</strong> has been cancelled.</p>
                <br/>
                <p>Best regards,<br/>FlashShop Team</p>
                """
            });
        }

        if (!existingKeys.Contains("DailySalesReport"))
        {
            templates.Add(new NotificationTemplate
            {
                Id = Guid.NewGuid(),
                Key = "DailySalesReport",
                Subject = "Daily Sales Report - {{Date}}",
                IsActive = true,
                Body = """
                <h2>Daily Sales Report</h2>
                <p>This is an automated report generated by FlashShop system.</p>
                """
            });
        }

        if (templates.Any())
        {
            context.NotificationTemplates.AddRange(templates);
            await context.SaveChangesAsync();
        }
    }
}
